### ISSUE TITLE
[feature] [BE] Implement last.fm api call function

### ISSUE THREAD

**Issue by c301hoon** [C301-Inc/Genie#63]
Describe the feature
--------------------
Get play count using lastfm_id, track title

**Data**

* 

**Technical Details**
- [ ] Implement in Genie/genie/server/backend/utils/lastfm.py

Minimum Requirements
--------------------
**Acceptance Criteria**
- [ ] nothing

**Comment by pillip** [comment]
@c301hoon 
I'd like to contribute this issue, please provide more information about the last.fm API.

**Comment by c301hoon** [comment]
You can find details here. (https://www.last.fm/api)

We will get discord user's track play count using last.fm

**Comment by pillip** [comment]
@c301hoon 
Can I assume that only people whose last.fm id is registered in the DB can use the api?
If the user doesn't have a last.fm id, we can just raise an error, right?

**Comment by c301hoon** [comment]
Yes, you're right

**Comment by pillip** [comment]
@c301hoon 
Thx.
