### ISSUE TITLE
[feature] [BE] Implement GetTracksCount query

### ISSUE THREAD

**Issue by c301hoon** [C301-Inc/Genie#65]
Describe the feature
--------------------
Implement GetTracksCount query to get live tracks' last.fm count

**Data**

* GetTracksCount query

**Technical Details**
- [ ] Return list of live tracks and each counts

Minimum Requirements
--------------------
**Acceptance Criteria**
- [ ] nothing

**Comment by pillip** [comment]
@c301hoon 
Can I resolve #65 #66 in one branch and PR?

**Comment by c301hoon** [comment]
@pillip Of course, you can.
